sudo: required

services:
- docker

language: java

jdk:
- oraclejdk8

before_install:
- mkdir -p output
- docker pull asciidoctor/docker-asciidoctor

script:
- docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -b html5 docs/index.adoc --out-file docs-build/index.html

after_error:
- docker logs asciidoc-to-html

after_failure:
- docker logs asciidoc-to-html

after_success:
- bash <(curl -s https://codecov.io/bash)
- cd docs-build
- git init
- git config user.name "travis@travis-ci.org"
- git config user.email "Travis CI"
- git add . ; git commit -m "Deploy to GitHub Pages"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1

branches:
  except:
  - gh-pages

cache:
  directories:
  - $HOME/.m2