sudo: required
language: java

jdk:
  - oraclejdk8

install: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip -B -V

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash ci/push_to_gh-pages.sh

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.m2