sudo: required
language: java

services:
  - docker

jdk:
  - oraclejdk8

before_install:
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

script:
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -b html5 docs/index.adoc --out-file docs/index.html

after_error:
  - docker logs asciidoc-to-html

after_failure:
  - docker logs asciidoc-to-html

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash ci/push_to_gh-pages.sh

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.m2